---
language: node_js
node_js:
  - 'lts/dubnium'
cache:
  directories:
    - node_modules
before_script: yarn build
script: yarn test
deploy:
  fqdn: kansu.co
  github_token: $GITHUB_TOKEN
  local-dir: public
  provider: pages
  skip_cleanup: true
  target-branch: gh-pages
