---
language: node_js
node_js:
  - 'stable'
cache:
  directories:
    - node_modules
  yarn: true
script: yarn build
deploy:
  fqdn: kansu.co
  github_token: $GITHUB_TOKEN
  local-dir: public
  provider: pages
  skip_cleanup: true
  target-branch: gh-pages
